"""Add created_at to memos

Revision ID: 1a0c1401a245
Revises: 6d80d36464fe
Create Date: 2025-05-09 12:17:32.587682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a0c1401a245'
down_revision: Union[str, None] = '6d80d36464fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memos', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memos', 'created_at')
    # ### end Alembic commands ###
