"""Insert Relationship , Delete Writer Column

Revision ID: 69c24eaa18ac
Revises: 1a0c1401a245
Create Date: 2025-05-16 16:45:26.690856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '69c24eaa18ac'
down_revision: Union[str, None] = '1a0c1401a245'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_memos_user_id', table_name='memos')
    op.create_foreign_key(None, 'memos', 'users', ['user_id'], ['id'])
    op.drop_column('memos', 'writer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memos', sa.Column('writer', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'memos', type_='foreignkey')
    op.create_index('ix_memos_user_id', 'memos', ['user_id'], unique=False)
    # ### end Alembic commands ###
