"""Initial migration

Revision ID: 86f7f5fced77
Revises: 
Create Date: 2025-03-27 17:48:55.133911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86f7f5fced77'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memos', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_memos_user_id'), 'memos', ['user_id'], unique=False)
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('user_id', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('user_pw', sa.String(length=255), nullable=True))
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_name', table_name='users')
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.create_index(op.f('ix_users_user_pw'), 'users', ['user_pw'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_pw'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.create_index('ix_users_name', 'users', ['name'], unique=False)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.drop_column('users', 'user_pw')
    op.drop_column('users', 'user_id')
    op.drop_column('users', 'username')
    op.drop_index(op.f('ix_memos_user_id'), table_name='memos')
    op.drop_column('memos', 'user_id')
    # ### end Alembic commands ###
